#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters"
    exit 1
fi

file=$1

ofile=${file%.*} 


echo "Compiling with....std c++11....."


if g++ -std=c++11 "$1" -lglut -lGL -lGLEW -lGLU -o "$ofile".out; then 
	echo "Success!";
	./$ofile.out
else 
	echo "Failure"; 
fi